### ISSUE TITLE
wrapXXX props for ILI

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#168]
#### Describe the desired behavior

Maybe we want wrapTitle, wrapSubtitle and wrapInfo for ILI, like what we did for R and Ng?

#### Describe the current behavior

there are no props that control that. Only style class overrides.

**Comment by emclaug2** [comment]
This'll require a little bit more research due to style limitations within RN.

**Comment by emclaug2** [comment]
Look into the `numberOfLines` and `ellipsizeMode` props.

**Comment by jeffvg** [comment]
This depends on the path taken for RN paper v5 and material design versions (v2 or v3)

**Comment by daileytj** [comment]
Fix this for RNP 4 and we can revisit when/if we upgrade to RNPv5
