### ISSUE TITLE
Header should blend with status bar on Android devices

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-component-library#186]
#### Describe the desired behavior
The header should blend behind the StatusBar on android devices (particularly those with a notch).

![image](https://user-images.githubusercontent.com/29152776/128889227-20872a61-2710-4a13-9b18-dcadaf53b16b.png)

#### Describe the current behavior
Currently the Header is drawn below the StatusBar on Android devices.

![image](https://user-images.githubusercontent.com/29152776/128889386-ea668c5e-f17e-4737-91ba-fceee0d6d5f0.png)

#### Is this request related to a current issue?
This is related to work from the EMCB project.

#### Additional Context

The StatusBar has a `translucent` prop that will allow us to draw content behind it (if we set `backgroundColor` to 'transparent'). However, setting this property currently causes some misalignment with the content because SafeAreaView does not do anything on Android (see https://github.com/facebook/react-native/issues/17371). We will need to manually add a top padding in the Header on Android devices.

**Comment by daileytj** [comment]
The quick and dirty solution above still needs some investigation since it leaves the middle content visible when collapsed.

**Comment by daileytj** [comment]
Fixed by #339
