### ISSUE TITLE
CollapsibleHeaderLayout should support other scroll containers

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-component-library#218]
#### Describe the desired behavior
The user should be able to use the CollapsibleHeaderLayout with any type of scrollable container they wish (ScrollView, KeyboardAvoidingScrollView, FlatList, SectionList).

#### Describe the current behavior
The CollapsibleHeaderLayout uses a hard-coded ScrollView element. 

#### Is this request related to a current issue?
This is something that we identified during initial implementation as a likely area that we would want to expand support. It has recently come up within the CRDS WiFi Wiring team.

#### Additional Context

This is particularly an issue because React Native doesn't let you render a FlatList inside of a ScrollView. So if a team (like CRDS) wants to use a FlatList to display their content (because it does virtualization and offers better performance), they can't and have to use the ScrollView which offers no optimization or performance.

There are a couple of ways we can do this:
1. Let the user pass in the element themselves. We would then just take the first child element, add the necessary props to it for use in the CollapsibleHeaderLayout (ref, scrollThrottle, etc.) and wrap the children in an animated view.
2. Restrict which options are allowed and expose a prop for selecting which item to use as the scroll container. Then expose another prop that will let the user spread props to the scroller (particularly important if using a flatlist or a sectionlist). 

Number 1 seems like the more graceful approach, but in my initial exploration, it caused issues with performance because the React.clone function was getting called too often. Number 2 introduces a lot of complexity to the typings.

**Comment by surajeaton** [comment]
Here are the four ways we can do this:
Option 1:
Pass a scroll component as a children with props and then we clone it and add the onScroll behavior
example: 
`children={<FlatList {...everything}/>`

Option 2 (typings for this get confusing): 
Pass ScrollComponent as a string and scrollComponentProps as a separate prop
example:
`ScrollComponent={'flatlist'}
 scrollComponentProps={{...FlatListProperties}}`
 
Option 3 (typings for this get confusing):
Pass ScrollComponent as a prop and scrollComponentProps as a separate prop
`ScrollComponent={FlatList}
 ScrollComponentProps={{...FlatListProperties}}`

Option 4:  
Call our function to update the header onScroll
` ScrollComponent={
            ({ updateHeader }) =>
                <FlatList 
                    prop1={prop1} 
                    prop2={prop2} 
                    data={myData} 
                    onScroll={(e) => {
                        /* do whatever they want */
                        /* call our function to update the header */
                        updateHeader(e);
                    }}
            />
                    
        }`
