### ISSUE TITLE
Use react-native-paper Text component in favor of our custom Typography component

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-component-library#309]
#### Describe the desired behavior
Look into what it would take to configure the react-native-paper Text component to use in favor of our custom Typography component.

#### Additional Context

There are new font configurations and the addition of a `<Text>` component in the react-native-paper v5 library. If it's possible to leverage these to minimize maintenance by replacing our `<Typography>` component this would be ideal. If this does not seem feasible without an abundance of customization and overrides then we can close this and continue maintaining the library as is.

**Comment by joebochill** [comment]
I believe we have already made this update with the MD3 changes, with the exception of the custom Overline component which remains in our library. Everything else has been switched over to a regular Text from RNP right?

**Comment by surajeaton** [comment]
This has already been addressed.
