### ISSUE TITLE
InfoListItem - Subtitle color should be neutral variant 30 

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-native-component-library#413]
#### Describe the bug / expected behavior
Issue is found https://github.com/etn-ccis/blui-react-native-component-library/pull/410#issuecomment-1777616432

Currently, InfoListItem subtitle color is `theme.colors.onSurfaceVariant`
It should be updated to `theme.colors.neutralVariant.neutral30`

#### What are the steps to reproduce?
1. yarn start
2. Scroll to InfoListItem example
3. Subtitle seems to be lighter than expected

#### Screenshots / Screen recording
![Simulator Screenshot - iphone 12 pro - 2023-10-25 at 15 46 18](https://github.com/etn-ccis/blui-react-native-component-library/assets/120575281/f3769a68-94ab-4278-8367-9771b5eff344)

![277739793-314d297e-e5ac-4691-a521-e509d7b0fe81](https://github.com/etn-ccis/blui-react-native-component-library/assets/120575281/66400155-6279-43c1-af71-6f91e5bef452)

#### Code snippet / Link to minimum reproduction example

```

```

#### Suggested fix

Update https://github.com/etn-ccis/blui-react-native-component-library/blob/9ae356d318447c6c679fbdfb3893403510119aa4/components/src/md3/InfoListItem/InfoListItem.tsx#L111

To use:
`theme.colors.neutralVariant.neutral30`

**Comment by ektaghag-eaton** [comment]
<img width="390" alt="Screenshot 2023-10-30 at 3 13 22 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/133877691/4c65b546-4138-4055-be75-84d3a3b0f406">


InfolistItem Subtitle is currently `#44474E `.
And font-family is OpenSans-Regular

**Comment by huayunh** [comment]
Interesting. So maybe it was a rendering issue?

**Comment by huayunh** [comment]
can we take a screenshot in extra large font size to better visually examine the color?

**Comment by ektaghag-eaton** [comment]
> can we take a screenshot in extra large font size to better visually examine the color?

Increase the text size on the iOS simulator to take Screenshots 
<img width="389" alt="Screenshot 2023-10-31 at 2 04 23 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/133877691/28df881a-922b-4faa-9af9-976ac7a82642">

Please check

**Comment by huayunh** [comment]
that looks good, thank you Ekta!
