### ISSUE TITLE
Hero - CSS doesn't match Figma.

### ISSUE THREAD

**Issue by ektaghag-eaton** [etn-ccis/blui-react-native-component-library#422]
#### What are the steps to reproduce?
1. Go to the showcase demo
2. Go to the hero example

Inspect component and check CSS for Label prop (text below channel Value)
**Hero prop CSS:
Label - font-weight should be 500, colour should be #44474E**
#### Screenshots / Screen recording
<img width="115" alt="Screenshot 2023-10-27 at 12 07 46 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/133877691/1f8008da-72eb-405c-9c3b-df9ac0912837">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Anything else to add?
**Recheck Color, size, font-weight.**

**Comment by huayunh** [comment]
That text should be a "Title Medium" with a font color of "on surface variant"

**Comment by huayunh** [comment]
Leaving this open to remind us to update the changelog
