### ISSUE TITLE
Icon spacing / sizing not correct in DrawerNavItems

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-component-library#457]
#### Describe the bug / expected behavior

Spacing is not correct between icon/text when viewing the DrawerNavItems in RTL. Refer to the original bug reported here on showcase: https://github.com/etn-ccis/blui-react-native-showcase-demo/issues/114

#### What are the steps to reproduce?
1. Run the showcase
2. Switch to RTL
3. Open the drawer and observe the incorrect spacing

#### Screenshots / Screen recording
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/29152776/88dff651-9938-4892-9922-a49dbbd5bab8)

#### Your environment information
N/A

#### Suggested fix
I suspect that in the InfoListItem, there's a fixed width container that provides the spacing you see between the icon and the text. The icon is still left-aligned in that container when in RTL mode which causes there to be no space. I think the fix may have something to do with that.

#### Anything else to add?
We need to _revert_ the changes that were made to the icon `direction` property. These icons should not be flipped (they are non-directional icons). Instead, we need to identify the underlying cause for why the spacing is not correct at the component level and fix it.

**Comment by surajeaton** [comment]
Seems to be fixed already:
![Simulator Screenshot - iphone 12 pro - 2023-12-15 at 16 23 20](https://github.com/etn-ccis/blui-react-native-component-library/assets/120575281/f98af8ae-1016-44b8-bf2d-9b7794c9fee9)
