### ISSUE TITLE
Header does not collapse completely

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-component-library#459]
#### Describe the bug / expected behavior
Header does not collapse completely. Is this an issue with the safe area height?

#### Screenshots / Screen recording

![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/29152776/0dc6e663-a42e-4a5e-8d32-f9ec576623dc)

#### Anything else to add?

If this is only an issue for the Header in the middle of the page, it can be ignored. Verify that it's working as expected when it's at the top of the screen (intended use) and if so, this issue can be closed.

**Comment by ArshdeepSingh3-eaton** [comment]
The Header was not collapsing completely because it is supposed to be used at the top of screen 
the status Bar is Supposed to bring the header design in alignment as the height for status bar is added in the total height of Header
it's implemented at the wrong Place

**Comment by huayunh** [comment]
We can close this if the header looks correct at the correct place... which it does.
