### ISSUE TITLE
Incorrect color on battery icon

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-native-component-library#462]
#### Describe the bug / expected behavior
The color of the battery (icon?) feels too light. This may just be a rendering issue from teams. Verify that the correct colors from design are being used.
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/29152776/a87f7e34-7a0e-47e1-8a2f-c4c461c3a1f8)

From https://github.com/etn-ccis/blui-react-native-themes/issues/57

**Comment by ektaghag-eaton** [comment]
Fixed https://github.com/etn-ccis/blui-react-native-component-library/pull/482
