### ISSUE TITLE
Update readmes and provide new screenshots

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#467]
#### Describe the bug / expected behavior

Given how drastically different our components are compared to ~3 years ago, the following component documentation needs an updated screenshot:
* Channel Value
* Drawer (no screenshots at all)
* Empty states
* Header
* Hero
* Info List Item
* Mobile stepper (bad screenshot: image size too big; should focus on just the stepper)
* Score Card
* Typography
* User Menu

The following component needs an update in the content:
* Typography

**Comment by ektaghag-eaton** [comment]
BLUI-5060

**Comment by huayunh** [comment]
Resolved with #498
