### ISSUE TITLE
Grade avatar background color in dark theme

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#473]
## Describe the bug / expected behavior
In dark theme, grade avatars' background color should match the custom "filled container" colors. This is mostly for the yellow grade color to not be too "glowy" in the dark.

Left: Current implementation; right: design
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/a2657349-a37e-429e-afeb-f4caeb1aafe1)

## full design rationale:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/9fa1a4da-df07-4fc9-a3c4-beaa1878fa30)
(oops sorry, the orange block on the bottom right corner should have said "orange filled container")

## To Reproduce
In React Native showcase demo, scroll to the grades part. Turn on dark theme. Observe.

**Comment by ektaghag-eaton** [comment]
BLUI-5065
