### ISSUE TITLE
Empty state description font color

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#475]
#### Describe the bug / expected behavior

The description of an Empty State should be colored `on-surface-variant`.

#### Screenshots / Screen recording
Dev:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/47e93643-5f28-4e80-9175-939a988079c9)

Design:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/1cb867cd-9753-4335-9cb5-29956098a7c2)

**Comment by huayunh** [comment]
Also why is that icon color so dark? I remember this already changed to the correct `disabled` color. Perhaps it renders differently?

**Comment by huayunh** [comment]
Related: https://github.com/etn-ccis/blui-react-native-component-library/issues/462

**Comment by ektaghag-eaton** [comment]
> Also why is that icon color so dark? I remember this already changed to the correct `disabled` color. Perhaps it renders differently?
> 
> Related: #462

Fixed [here](https://github.com/etn-ccis/blui-react-native-component-library/pull/469/files#diff-191b5b98240e6992eabac13c360e9cb2d66338dfb7bba03b0d97595a47c7e034R101). But not merge yet.

**Comment by ektaghag-eaton** [comment]
To update font color of description - BLUI-5066

**Comment by ektaghag-eaton** [comment]
> To update font color of description - BLUI-5066

Fixed here [482](https://github.com/etn-ccis/blui-react-native-component-library/pull/482)
