### ISSUE TITLE
Info List Item's leading icon feels very bright in the dark theme

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#476]
#### Screenshots / Screen recording
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/7b773b9f-53cb-44f7-b304-9b54a2906777)

#### Suggested fix
I thought this was already addressed, but just in case... the icon color should be on-surface-variant.

**Comment by ektaghag-eaton** [comment]
BLUI-5068

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-native-component-library/pull/482)
