### ISSUE TITLE
Flip the Icon Switch for RTL

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#477]
##  Describe the desired feature/functionality
Icon Switch should be flipped on RTL

![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/ce580172-00ee-4e2e-98a3-e13566ceeb73)

## Additional Context

After experiment around and risking never being able to set my phone and computers back to English again, I learned:

- Android flips (This is a phone in Material Design 3)
- iPhone flips
- Windows flips
- Material UI flips

No comment from Material Design themselves on this matter, however. I do not see a need to flip it (there's no directionality), but it's better to stay consistent with user's operating system.

**Comment by huayunh** [comment]
This is a screenshot from showcase's design audit, showing React Native Paper's default RTL switch on iOS:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/3fb3091c-95dd-4aab-a7c5-74e503cd97c6)

**Comment by ektaghag-eaton** [comment]
BLUI-5069

**Comment by ektaghag-eaton** [comment]
Fixed https://github.com/etn-ccis/blui-react-native-component-library/pull/487
