### ISSUE TITLE
Score Card Header Action Icons default color should be onSurfaceVariant

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#488]
# Describe the bug / expected behavior

The action icons in the score card header currently take the same color as the header text color `onPrimaryContainer`. Expect the icons to be controlled separate from the header text color and use `onSurfaceVariant` instead

# Design Expectation

![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/2d9bca5e-1591-47d1-8870-ab52fb73f84f)

# Suggested fix

This default color shall be `onSurfaceVariant`. You likely need a new separate prop to control the color behavior.

https://github.com/etn-ccis/blui-react-native-component-library/blob/8c9c3c4863b12cebdeb1a595fab731a52ed3add3/components/src/core/ScoreCard/ScoreCard.tsx#L398

Remember to change:
* JSDocs (plus any in code comments)
* Readme
  * Including the screenshot, if necessary

# Anything else?

I noticed this while reviewing #482

**Comment by ektaghag-eaton** [comment]
Fixed
