### ISSUE TITLE
Increase list item tag border radius to 4px

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#500]
#### Describe the desired feature/functionality
Since Material Design makes everything round, let's make list item tag round too!

![List Item Tag](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/6a20e5c7-247a-4137-bb6c-cc4b3e404a91)

#### Suggested implementation details
Update this multiplier to 4
https://github.com/etn-ccis/blui-react-native-component-library/blob/77240c297eee609e9a6c8f8974048bf460d6c399/components/src/core/ListItemTag/ListItemTag.tsx#L57

**Comment by huayunh** [comment]
BLUI-5091

**Comment by ektaghag-eaton** [comment]
Fixed.
