### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#523]
Remove unused branches!

![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/31dd6212-f48b-4b46-9094-ed1009bf5913)

**Comment by ektaghag-eaton** [comment]
Done.

<img width="1397" alt="Screenshot 2024-01-17 at 2 21 35 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/133877691/daa5599b-9d62-4403-a7fe-6f836816d077">
