### ISSUE TITLE
Header is being chopped off in Tablet

### ISSUE THREAD

**Issue by manojleaton** [etn-ccis/blui-react-native-component-library#531]
#### What are the steps to reproduce?
1. Run the React native component library showcase demo app in tablet
2. Observe the header
3. [Jira](https://eaton-corp.atlassian.net/browse/BLUI-5272)

#### Screenshots / Screen recording
<img width="910" alt="Screenshot 2024-01-26 at 9 51 31 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/130662346/63143819-6ca8-4d84-b4aa-12b04944da4e">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment]
Related to https://github.com/etn-ccis/blui-react-native-workflows/issues/165

**Comment by surajeaton** [comment]
Fixed in https://github.com/etn-ccis/blui-react-native-component-library/pull/538
