### ISSUE TITLE
Iconwrapper.md file does not exist

### ISSUE THREAD

**Issue by priyankakmEaton** [etn-ccis/blui-react-native-component-library#578]
#### What are the steps to reproduce?
1. Go to Icons.md
2. Click on https://github.com/etn-ccis/blui-react-native-component-library/blob/master/docs/IconWrapper.md , in Icon as a prop section 
3. IconWrapper.md file does not exist

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment]
We can remove the link as we no longer support using IconWrapper
