### ISSUE TITLE
MobileStepper text variant is misaligned

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-native-component-library#583]
#### Describe the bug / expected behavior
MobileStepper text variant is misaligned

#### What are the steps to reproduce?
1. Found in https://github.com/etn-ccis/blui-react-native/pull/62#issuecomment-2174311787

#### Screenshots / Screen recording
<img width="1077" alt="Screenshot 2024-06-18 at 3 23 24 PM" src="https://github.com/etn-ccis/blui-react-native-component-library/assets/120575281/af4ca390-2737-46cb-8050-17577441a04b">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by surajeaton** [comment]
We might need to have this updated in the react-native component library and publish an updated beta version as we did for a couple of other issues like this that we noticed https://github.com/etn-ccis/blui-react-native-component-library/pull/580/files

**Comment by ektaghag-eaton** [comment]
Not able to reproduce this issue [here](https://brightlayer-ui-components.github.io/react-native-dev/components/mobile-stepper/examples)
