### ISSUE TITLE
Should be able to add an onPress event to DrawerHeader

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-native-component-library#84]
#### Describe the desired behavior

I want to be able to add a touch event to the entirety of the DrawerHeader.

#### Describe the current behavior

Cannot add an onPress event to DrawerHeader — only the icon is clickable.

#### Additional Context
This was sparked by a desire to click the DrawerHeader to go to the 'home' route instead of having to add an extra home item in the navigation items.

Make the root element of the DrawerHeader a TouchableWithoutFeedback instead of a plain View so an onPress event can be used. The type for DrawerHeaderProps should be updated to extend TouchableWithoutFeedbackProps instead of ViewProps (this will remain backwards compatible because TouchableWithoutFeedback is a superset of ViewProps).

**Comment by jeffvg** [comment]
We talked about this and shouldn't be too bad.....click nav icon should not fire the header click event
